# Generated by Django 2.2.4 on 2019-09-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapti_app', '0002_auto_20190811_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='my_category',
        ),
        migrations.AddField(
            model_name='item',
            name='my_category',
            field=models.ManyToManyField(to='tapti_app.Category'),
        ),
    ]
