# Generated by Django 2.2.4 on 2019-09-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapti_app', '0003_auto_20190908_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
