# Generated by Django 2.2.4 on 2019-09-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapti_app', '0004_item_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_on_navbar',
            field=models.BooleanField(default=False),
        ),
    ]
