# Generated by Django 2.2.4 on 2019-09-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapti_app', '0006_category_newly_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='newly_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='my_category',
            field=models.ManyToManyField(related_name='item', to='tapti_app.Category'),
        ),
    ]
