# Generated by Django 2.2.4 on 2019-09-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapti_app', '0008_auto_20190910_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.FileField(upload_to='images/slider/'),
        ),
    ]
